"""
Training Configuration.

Split of responsibilities:
  - `schema.py`  — everything derived from the GAME (enemy tables, wave
                   templates, curriculum, feature layout, decoder constants).
                   Generated by `npm run ai-schema`, never hand-edited.
  - this file    — everything that is a TRAINING choice (hyperparameters,
                   reward shaping, episode length, checkpointing).

Architecture:
  - State:  schema.INPUT_SIZE features (162 at schema v2)
  - Action: template_idx (32 slots) + 4 continuous factors in [0,1]
  - Reward: 4 terms (DEATH, DRAMA, SWARM_SIZE, PROGRESSION)
"""

from schema import (  # re-exported for convenience  # noqa: F401
    INPUT_SIZE,
    NUM_SCALAR,
    NUM_SPATIAL,
    NUM_BINS,
    MAX_TEMPLATE_SLOTS,
    TEMPLATE_COOLDOWN_WAVES,
    ENEMY_TYPES,
    NUM_ENEMY_TYPES,
    ENEMY_BASE_HP,
    ENEMY_ARMOR,
    AIR_ENEMIES,
    ETHEREAL_ENEMIES,
    MAX_WAVE_DURATION_MS,
    MIN_SPAWN_DELAY_MS,
    DPS_RAMP_FLOOR,
    DPS_RAMP_COUNT,
    DPS_RAMP_HP_MULT,
    EPISODE_LENGTH,
)

# === SERVER ===
SERVER_HOST = "localhost"
SERVER_PORT = 3001
DASHBOARD_PORT = 3002

# === ACTION SPACE ===
NUM_CONTINUOUS = 4
OUTPUT_SIZE = MAX_TEMPLATE_SLOTS + NUM_CONTINUOUS  # 36

# Ordered names of the continuous params (for logging + debugging).
CONTINUOUS_PARAM_NAMES = ["count", "spawn_delay", "hp_mult", "variation"]

# === TRAINING ===
LEARNING_RATE = 0.0003
CLIP_EPSILON = 0.2
ENTROPY_COEF = 0.05
VALUE_COEF = 0.5
BATCH_SIZE = 16
UPDATE_EPOCHS = 4

# No discounting: one wave = one independent decision, and the reward for a
# wave is fully observed the moment it ends. There is no bootstrapping across
# waves, so the setup is a contextual bandit rather than a horizon-1 MDP.
# Kept explicit so nobody re-adds a GAMMA that silently does nothing.
USE_DISCOUNTING = False

# === REWARD — Term 1: DEATH ===
REWARD_GAME_OVER_PENALTY = -0.3   # multiplied by early-wave scaling in reward._death_penalty
REWARD_GAME_OVER_CAP = -3.5       # absolute floor for the death term

# === REWARD — Term 2: DRAMA (damage + path-progress merged) ===
# Sweet zone: 1-5% HP loss per wave = "permanently demanding".
DAMAGE_SWEET_MIN = 0.01           # >= 1% HP lost = into sweet zone
DAMAGE_SWEET_MAX = 0.05           # <= 5% = peak
DAMAGE_HARD_THRESHOLD = 0.20      # damage > 20% starts linear penalty
REWARD_DAMAGE_SWEET_PEAK = 0.40   # peak reward for exact targeting
REWARD_DAMAGE_ZERO_PENALTY = -0.10  # small penalty below SWEET_MIN (boring wave)
REWARD_DAMAGE_HARD_SLOPE = 3.0    # penalty factor per full HP overrun
PROGRESS_NEAR_MISS_LOW = 0.65     # enemies reached 65-90% path = near-miss sweet
PROGRESS_NEAR_MISS_HIGH = 0.90
PROGRESS_OVERFLOW_THRESHOLD = 0.95
REWARD_NEAR_MISS_PEAK = 0.50
REWARD_OVERFLOW = -0.80
REWARD_PROGRESS_SLOPE = 0.30      # mild positive for intermediate progress

# === REWARD — Term 3: SWARM_SIZE ===
# Phase 5.14 dampening: earlier values (slope=0.003, cap=8.0) made big
# unarmored swarms net +1-8 reward, dwarfing the sweet-spot peak (+0.4) and
# the progression cap (+0.5). The net exploited the path of least resistance
# (huge zombie waves the bot trivially clears → 0 damage → max swarm bonus,
# 77% zero-damage waves observed). Halved slope + 4x lower cap puts swarm
# reward back in line so the sweet spot is the attractive target again.
# With slope 0.0015 and cap 2.0 the bonus saturates at 1353 enemies.
SWARM_SMALL_THRESHOLD = 20        # below this = tiny wave (penalty)
SWARM_SMALL_PENALTY = -0.10
SWARM_SIZE_SLOPE = 0.0015         # +0.0015 per enemy above threshold
SWARM_SIZE_CAP = 2.0              # max swarm bonus

# === REWARD — Term 4: PROGRESSION ===
PROGRESSION_SLOPE = 0.02          # +0.02 per wave_num
PROGRESSION_CAP = 0.5             # plateau at wave 25+

# === BOT DISTRIBUTION (client-side selection weight) ===
BOT_WEIGHTS = {"strategist": 1.0}

# === CHECKPOINTS ===
CHECKPOINT_INTERVAL = 10
CHECKPOINT_DIR = "checkpoints"

# === EXPORT ===
EXPORT_DIR = "../public/assets/ai/wave-director"
