"""
Training Configuration.

Split of responsibilities:
  - `schema.py`  — everything derived from the GAME (enemy tables, wave
                   templates, curriculum, feature layout, decoder constants).
                   Generated by `npm run ai-schema`, never hand-edited.
  - this file    — everything that is a TRAINING choice (hyperparameters,
                   reward shaping, episode length, checkpointing).

Architecture:
  - State:  schema.INPUT_SIZE features (162 at schema v2)
  - Action: template_idx (32 slots) + 4 continuous factors in [0,1]
  - Reward: 4 terms (DEATH, DRAMA, SWARM_SIZE, PROGRESSION)
"""

from schema import (  # re-exported for convenience  # noqa: F401
    INPUT_SIZE,
    NUM_SCALAR,
    NUM_SPATIAL,
    NUM_BINS,
    MAX_TEMPLATE_SLOTS,
    TEMPLATE_COOLDOWN_WAVES,
    ENEMY_TYPES,
    NUM_ENEMY_TYPES,
    ENEMY_BASE_HP,
    ENEMY_ARMOR,
    AIR_ENEMIES,
    ETHEREAL_ENEMIES,
    MAX_WAVE_DURATION_MS,
    MIN_SPAWN_DELAY_MS,
    DPS_RAMP_FLOOR,
    DPS_RAMP_COUNT,
    DPS_RAMP_HP_MULT,
    EPISODE_LENGTH,
)

# === SERVER ===
SERVER_HOST = "localhost"
SERVER_PORT = 3001
DASHBOARD_PORT = 3002

# === ACTION SPACE ===
NUM_CONTINUOUS = 4
OUTPUT_SIZE = MAX_TEMPLATE_SLOTS + NUM_CONTINUOUS  # 36

# Ordered names of the continuous params (for logging + debugging).
CONTINUOUS_PARAM_NAMES = ["count", "spawn_delay", "hp_mult", "variation"]

# === TRAINING ===
LEARNING_RATE = 0.0003
CLIP_EPSILON = 0.2
VALUE_COEF = 0.5

# Batch raised from 16. Sixteen samples of a reward that ranges roughly -30..+2,
# drawn from four clients contributing consecutive correlated waves, gave a
# gradient direction that was mostly noise — and during the curriculum (waves
# 1-30, where the mask has a single option) the categorical head gets no signal
# at all while still filling batch slots. At timescale 75 with four clients this
# is a couple of minutes of wall time.
BATCH_SIZE = 128
MINIBATCH_SIZE = 32
UPDATE_EPOCHS = 4

# Stop the epoch loop early once the policy has moved too far from the one that
# collected the data. Four epochs over the same samples with no KL guard is how
# PPO quietly turns into an unclipped policy-gradient step.
TARGET_KL = 0.02

# Entropy bonus on the template head only.
#
# The continuous entropy term was measured on the pre-sigmoid Gaussian, so
# maximising it simply pushed `log_std` up — and a wide Gaussian squashed
# through a sigmoid piles mass on the range ENDPOINTS. That is anti-exploration
# in factor space: waves collapse to min/max count and min/max HP, which is the
# opposite of the "varied waves" goal. `log_std` is clamped instead (see
# model.py) and only the categorical head keeps a bonus.
ENTROPY_COEF = 0.02

# Effective window for the reward-scaling statistic. A lifetime count would
# stop adapting once it grew large, which is wrong for a reward that keeps
# shifting as the policy improves and the wave numbers climb.
REWARD_SCALE_WINDOW = 2000

# How many waves a single client may accumulate before its trajectory is cut
# and bootstrapped. Long survivors would otherwise contribute nothing.
TRAJECTORY_FLUSH_LENGTH = 32

# Run one client deterministically every N episodes so the metrics describe the
# policy we actually export, not the exploration noise around it.
DETERMINISTIC_EVAL_EVERY = 25

# Waves are NOT independent, and treating them as such inverted the objective.
#
# The player never heals (`healBase()` has no production caller), so HP is a
# one-way resource across a whole run. The per-wave optimum requires 1-5% HP
# loss, which at ~3% per wave kills the player in ~33 waves — and the old
# bandit framing paid the full sweet-spot reward the entire way down, charging
# only a single -3.5 at the end. "Bleed the player out and kill them at wave 30"
# scored ~+83 and beat every sustainable policy. That is why runs died at waves
# 5, 10 and 11 with the reward curve still climbing.
#
# Returns are now discounted along each client's trajectory, so the waves that
# set up a death are charged for it.
GAMMA = 0.9

# Generalised advantage estimation. 0.95 is the usual compromise between the
# bias of pure bootstrapping and the variance of full Monte-Carlo returns.
GAE_LAMBDA = 0.95

# === REWARD — Term 1: DEATH ===
# === REWARD v4 ================================================================
#
# v3 expressed the design goal as "the player should lose 1-5% of max HP every
# wave". Measured over ~9900 episodes that turned out to be unreachable and
# self-contradictory, and the agent correctly responded by doing nothing:
#
#   - Leak damage is `1 + floor((w-1)/10)` HP against 100 max HP, so damage is
#     QUANTISED. From wave 51 a single leak costs 6% and zero leaks cost 0%.
#     No value inside [1%, 5%] exists. Three of the four terms gated on that
#     band, so from W51 they were structurally dead.
#   - The player never heals (`healBase()` has only test callers, no research
#     restores lives) and the game has no win condition. 100 HP is the budget
#     for the entire run, so "1-5% every wave" IS death within 100 waves — the
#     very thing the DEATH term punished with -15..-30.
#   - Drama was read off `avg_progress`, the MEAN path progress. Drama lives in
#     the upper tail: 270 rats of which 5 reach 95% is tense, and the mean
#     reports 0.1. `near_miss_ratio` was already computed and thrown away.
#
# v4 therefore splits the two questions that v3 conflated:
#
#   DRAMA  — "was this wave exciting?"  Measured per wave on near_miss_ratio,
#            a fine-grained (step 1/count) upper-tail statistic.
#   PACING — "is the run the right length?"  Measured against an HP decay curve
#            across the whole run, where a 6-HP leak is a small step instead of
#            a jump across a band.
#
# === REWARD — Term 1: DEATH ===
# Relative to the target curve, not absolute. The run is SUPPOSED to end: an
# endless game with no healing has exactly one ending. Dying on schedule is
# free; dying at wave 10 is not. This removes v3's contradiction, where the
# reward's own optimum was an outcome the reward also punished.
TARGET_RUN_WAVES = 80             # the HP curve is drawn to hit zero here
# Cost of dying at wave 0, falling quadratically to 0.0 at TARGET_RUN_WAVES.
# Sized so a death outweighs the waves inside the discount horizon that set it
# up (1/(1-GAMMA) ~ 10 waves at ~1.3 each) — the property v3's -3.5 cap lacked,
# which made "bleed them out, then cash in" the winning line.
REWARD_DEATH_MAX = -40.0

# === REWARD — Term 2: DRAMA (near-miss distribution) ===
# Target a BAND of the fraction of enemies that get past 80% of the path.
# 0.25 means: a quarter of the wave nearly makes it. Zero is a walkover, 1.0 is
# a breach. A Gaussian, not a step: every wave gets a gradient telling it which
# way to move, which is what v3's cliff-shaped gates destroyed.
NEAR_MISS_TARGET = 0.25
NEAR_MISS_SIGMA = 0.18
REWARD_DRAMA_PEAK = 1.00          # value at exactly NEAR_MISS_TARGET
REWARD_DRAMA_IDLE = -0.30         # value as near_miss_ratio -> far from target
# A ratio is scale-free, so 1 leaker out of 4 would score as well as 25 out of
# 100. Damp small waves so the band cannot be farmed with a handful of enemies.
# Boss templates start at countRange [10,100], so full credit at 40 is reachable
# for every template in the set.
DRAMA_FULL_COUNT = 40

# === REWARD — Term 3: PACING (HP decay curve) ===
# Where the player's HP should be by now, and how sharply we insist on it.
# At 100 HP and TARGET_RUN_WAVES=80 the curve asks for ~1.25 HP per wave, which
# past W51 means one leak every four to five waves — coarse, but steerable via
# count and spawn delay, unlike the old per-wave band.
PACING_SIGMA = 0.18               # in HP fraction; ~18 HP of tolerance
# Magnitude of the PENALTY for being off the curve; 0 when exactly on it.
# Deliberately not a bonus: paying for being on schedule meant a policy that
# sent nothing still scored positive whenever the player happened to sit on the
# curve, which is the v3 collapse re-entering through a different door.
REWARD_PACING_PEAK = 0.60

# === REWARD — Term 4: SWARM_SIZE ===
# Unchanged in spirit: a tiebreaker inside the drama envelope, never the goal.
# Now gated on drama being positive rather than on the dead damage band.
SWARM_SMALL_THRESHOLD = 20        # below this = tiny wave (penalty)
SWARM_SMALL_PENALTY = -0.10
SWARM_SIZE_SLOPE = 0.0004
SWARM_SIZE_CAP = 0.30             # below the drama peak by design

# === OVERFLOW ===
# Everyone reached the base. That is a breach, not a near-miss, whatever the
# near-miss ratio says about it.
PROGRESS_OVERFLOW_THRESHOLD = 0.95
REWARD_OVERFLOW = -0.80

# === Damage bands — DISPLAY ONLY as of v4 ===
# No reward term gates on these any more. The dashboard still buckets waves by
# them (`damageSweetPct`, the damage-zone histogram) because "how much HP did
# that wave actually cost" stays the number a human wants to see.
DAMAGE_SWEET_MIN = 0.01
DAMAGE_SWEET_MAX = 0.05
DAMAGE_HARD_THRESHOLD = 0.20
PROGRESS_NEAR_MISS_LOW = 0.65     # still used by the progress histogram
PROGRESS_NEAR_MISS_HIGH = 0.90

# === BOT DISTRIBUTION (client-side selection weight) ===
BOT_WEIGHTS = {"strategist": 1.0}

# === CHECKPOINTS ===
CHECKPOINT_INTERVAL = 10
CHECKPOINT_DIR = "checkpoints"

# === EXPORT ===
EXPORT_DIR = "../public/assets/ai/wave-director"
