/**
 * AI Schema Generator.
 *
 * Writes `training-backend/generated/ai-schema.json` — the contract between the
 * TypeScript game and the Python training backend. Everything in it is derived
 * from the live configs, so the backend can never drift from the game the way
 * the hand-maintained `templates.py` / `wave_curriculum.py` / `config.py`
 * enemy tables did (they diverged for three months and were deleted).
 *
 * The JSON carries:
 *   - schema version + feature-block sizes (so Python can assert INPUT_SIZE)
 *   - the four order-sensitive vocabularies (enemies, towers, damage, armor)
 *   - enemy stats the backend needs (base HP, armor class, air flag, threat)
 *   - all wave templates with their ranges and gates
 *   - the curriculum template sequence
 *   - decoder constants (DPS ramp, duration cap, cooldown)
 *   - the endgame difficulty ramps, which the backend must apply too or it
 *     trains against a different HP curve than the game ships
 *
 * Run on demand:
 *   npm run ai-schema
 *
 * Also runs as a vitest spec on `npm test`, so the committed JSON is rewritten
 * after any config change; a stale commit shows up as a dirty working tree.
 */

import { describe, it, expect } from 'vitest';
import { writeFileSync, mkdirSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  AI_SCHEMA_VERSION,
  AI_ENEMY_ORDER,
  AI_TOWER_ORDER,
  AI_DAMAGE_TYPE_ORDER,
  AI_ARMOR_ORDER,
  AI_MAX_VALUES,
  ENEMY_THREAT_RATING,
  NUM_DPS_BINS,
  AI_EPISODE_LENGTH,
  NUM_BASE_FEATURES,
  NUM_AWARENESS_FEATURES,
  NUM_EFFECTIVE_DPS_FEATURES,
  NUM_WAVE_CONTEXT_FEATURES,
  NUM_TEMPLATE_RANGE_FEATURES,
  NUM_SCALAR_FEATURES,
  NUM_SPATIAL_FEATURES,
  ENCODED_STATE_SIZE,
} from '../../src/app/ai/core/ai-schema';
import {
  TEMPLATES,
  MAX_TEMPLATE_SLOTS,
  NUM_ACTIVE_TEMPLATES,
  TEMPLATE_COOLDOWN_WAVES,
  MAX_WAVE_DURATION_MS,
  MIN_SPAWN_DELAY_MS,
  DPS_RAMP_FLOOR,
  DPS_RAMP_COUNT,
  DPS_RAMP_HP_MULT,
  FAIRNESS_HEADROOM,
  FAIRNESS_ENGAGEMENT_SECONDS,
  FAIRNESS_MIN_COUNT,
} from '../../src/app/ai/core/templates';
import {
  WAVE_CURRICULUM,
  endgameHpMultiplier,
  enemyBaseDamageForWave,
} from '../../src/app/configs/wave-curriculum.config';
import { ENEMY_TYPES, type EnemyTypeId } from '../../src/app/configs/enemy-types.config';
import { GAME_BALANCE } from '../../src/app/configs/game-balance.config';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = resolve(__dirname, '../../training-backend/generated/ai-schema.json');

/**
 * How far the endgame ramps are pre-computed into the JSON. The backend reads
 * the table instead of re-implementing the formulas; beyond the table it clamps
 * to the last entry, which is correct because both ramps plateau (HP at 4.0×
 * from W80, leak damage keeps stepping but the table covers the training range
 * of EPISODE_LENGTH = 100 waves).
 */
const RAMP_TABLE_WAVES = 120;

function buildEnemies() {
  return AI_ENEMY_ORDER.map((id) => {
    const cfg = ENEMY_TYPES[id as EnemyTypeId];
    if (!cfg) throw new Error(`AI_ENEMY_ORDER references unknown enemy '${id}'`);
    return {
      id,
      baseHp: cfg.baseHp,
      baseSpeed: cfg.baseSpeed,
      armor: cfg.armorType,
      isAir: cfg.isAirUnit === true,
      threat: ENEMY_THREAT_RATING[id] ?? 1.0,
    };
  });
}

function buildTemplates() {
  return TEMPLATES.map((t, slot) => ({
    slot,
    id: t.id,
    name: t.name,
    description: t.description,
    enemies: t.enemies.map(([type, share]) => ({ type, share })),
    countRange: [t.countRange[0], t.countRange[1]],
    spawnDelayRange: [t.spawnDelayRange[0], t.spawnDelayRange[1]],
    hpMultRange: [t.hpMultRange[0], t.hpMultRange[1]],
    variationRange: [t.variationRange[0], t.variationRange[1]],
    minWave: t.minWave,
    spawnPattern: t.spawnPattern,
    requiresCapability: t.requiresCapability,
    bossOnly: t.bossOnly,
  }));
}

function buildRamps() {
  const hp: number[] = [];
  const leak: number[] = [];
  for (let w = 1; w <= RAMP_TABLE_WAVES; w++) {
    hp.push(endgameHpMultiplier(w));
    leak.push(enemyBaseDamageForWave(w));
  }
  return { waves: RAMP_TABLE_WAVES, endgameHpMultiplier: hp, enemyBaseDamage: leak };
}

function buildSchema() {
  return {
    _comment:
      'GENERATED by `npm run ai-schema` from the TypeScript configs. Do not edit by hand.',
    schemaVersion: AI_SCHEMA_VERSION,

    state: {
      inputSize: ENCODED_STATE_SIZE,
      numScalar: NUM_SCALAR_FEATURES,
      numSpatial: NUM_SPATIAL_FEATURES,
      numBins: NUM_DPS_BINS,
      blocks: {
        base: NUM_BASE_FEATURES,
        awareness: NUM_AWARENESS_FEATURES,
        effectiveDps: NUM_EFFECTIVE_DPS_FEATURES,
        waveContext: NUM_WAVE_CONTEXT_FEATURES,
      },
      templateRangeFeatures: NUM_TEMPLATE_RANGE_FEATURES,
    },

    orders: {
      enemies: [...AI_ENEMY_ORDER],
      towers: [...AI_TOWER_ORDER],
      damageTypes: [...AI_DAMAGE_TYPE_ORDER],
      armorTypes: [...AI_ARMOR_ORDER],
    },

    maxValues: { ...AI_MAX_VALUES },

    enemies: buildEnemies(),

    templates: {
      maxSlots: MAX_TEMPLATE_SLOTS,
      activeCount: NUM_ACTIVE_TEMPLATES,
      cooldownWaves: TEMPLATE_COOLDOWN_WAVES,
      list: buildTemplates(),
    },

    curriculum: {
      // Template ids only. The gold budget stays frontend-only — the backend's
      // reward function has nothing to do with player income.
      sequence: WAVE_CURRICULUM.map((e) => e.template),
      /**
       * Waves 1..N are pinned to the sequence (masked down to exactly one
       * template so the sampled action equals the shipped wave). From N+1 the
       * template head chooses freely under the normal availability mask.
       */
      forcedThroughWave: WAVE_CURRICULUM.length,
    },

    decoder: {
      maxWaveDurationMs: MAX_WAVE_DURATION_MS,
      minSpawnDelayMs: MIN_SPAWN_DELAY_MS,
      dpsRamp: { floor: DPS_RAMP_FLOOR, count: DPS_RAMP_COUNT, hpMult: DPS_RAMP_HP_MULT },
      fairness: {
        headroom: FAIRNESS_HEADROOM,
        engagementSeconds: FAIRNESS_ENGAGEMENT_SECONDS,
        minCount: FAIRNESS_MIN_COUNT,
      },
    },

    difficultyRamps: buildRamps(),

    player: {
      startHealth: GAME_BALANCE.player.startHealth,
      startCredits: GAME_BALANCE.player.startCredits,
    },

    training: {
      episodeLength: AI_EPISODE_LENGTH,
    },
  };
}

describe('ai schema generator', () => {
  it('writes training-backend/generated/ai-schema.json', () => {
    const schema = buildSchema();
    const json = JSON.stringify(schema, null, 2) + '\n';

    mkdirSync(dirname(OUT_PATH), { recursive: true });
    writeFileSync(OUT_PATH, json);

    // Derived sizes must stay self-consistent — a mismatch here means the
    // encoder and the backend would disagree on where every feature lives.
    expect(schema.state.inputSize).toBe(
      schema.state.numScalar + schema.state.numSpatial,
    );
    expect(schema.state.numScalar).toBe(
      schema.state.blocks.base +
        schema.state.blocks.awareness +
        schema.state.blocks.effectiveDps +
        schema.state.blocks.waveContext,
    );
    expect(schema.state.numSpatial).toBe(2 * schema.state.numBins);
  });

  it('every ordered enemy resolves to a real enemy config', () => {
    for (const e of buildSchema().enemies) {
      expect(ENEMY_TYPES[e.id as EnemyTypeId]).toBeDefined();
      expect(e.baseHp).toBeGreaterThan(0);
      expect(e.threat).toBeGreaterThan(0);
    }
  });

  it('every template enemy is in the ordered enemy vocabulary', () => {
    const known = new Set<string>(AI_ENEMY_ORDER);
    for (const t of buildSchema().templates.list) {
      for (const e of t.enemies) {
        expect(known.has(e.type), `template ${t.id} uses unknown enemy ${e.type}`).toBe(true);
      }
    }
  });

  it('every curriculum entry names an existing template', () => {
    const schema = buildSchema();
    const ids = new Set(schema.templates.list.map((t) => t.id));
    for (const id of schema.curriculum.sequence) {
      expect(ids.has(id), `curriculum references unknown template ${id}`).toBe(true);
    }
  });

  it('boss templates are only pinned to boss waves', () => {
    // `minWave` and `requiresCapability` are gates for FREE selection (from
    // `forcedThroughWave` + 1 onward); the curriculum deliberately introduces
    // content earlier than its gate — W2 runs rat_tide despite minWave 8. The
    // boss cadence is the one property the curriculum must not break, because
    // the milestone gold bonuses in game-balance.config are keyed to it.
    const schema = buildSchema();
    const byId = new Map(schema.templates.list.map((t) => [t.id, t]));
    schema.curriculum.sequence.forEach((id, i) => {
      const wave = i + 1;
      if (!byId.get(id)!.bossOnly) return;
      expect(wave % 10, `boss template ${id} pinned to non-boss wave ${wave}`).toBe(0);
    });
  });

  it('the curriculum covers every capability before it is required', () => {
    // A forced template bypasses `requiresCapability`, so the player must have
    // had a realistic chance to unlock it. Anti-air is reachable from wave 1
    // (archer targets air); anti-ethereal needs the ice-magic research, so the
    // first ethereal wave must not be the very first waves of a run.
    const schema = buildSchema();
    const byId = new Map(schema.templates.list.map((t) => [t.id, t]));
    const firstEthereal = schema.curriculum.sequence.findIndex(
      (id) => byId.get(id)!.requiresCapability === 'antiEthereal',
    );
    expect(firstEthereal, 'curriculum never requires anti-ethereal').toBeGreaterThan(-1);
    expect(firstEthereal + 1, 'anti-ethereal demanded too early to be researchable')
      .toBeGreaterThanOrEqual(8);
  });
});
